version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=apiPalabra'
      - 'MYSQL_ROOT_PASSWORD=vs'
      - 'MYSQL_ROOT_USER=root'
    volumes:
      # - './sql/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - './initSQL:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - 'PMA_HOST=mysql'
    ports:
      - '8080:80'
