services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=apiPalabra'
      # - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      # - 'MYSQL_USER=myuser'
      - 'MYSQL_ROOT_USER=root'
    ports:
      - '3306:3306'
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - 'PMA_HOST=mysql'
    ports:
      - '8080:80'
